---
kind: List
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: web-app
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: web-app
          tier: frontend
          track: canary
        name: web-app
      spec:
        containers:
        - name: web-app
          image: nginx:1.11.10-alpine
          env:
          - name: NODE_ENV
            value: canary
          - name: TRACK
            value: canary
          ports:
          - containerPort: 80
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: web-app
      tier: frontend
      track: canary
    name: web-app
  spec:
    ports:
    - port: 80
      targetPort: 80
    selector:
      app: web-app
    type: LoadBalancer

